### ISSUE TITLE
Enable additional cops

### ISSUE THREAD

**Issue by ybiquitous** [standardrb/standard-rails#10]
Hello. Let me ask a question about enabling additional cops for RuboCop Rails.

Please assume we have the following files to enable the `Rails/Pluck` cop:

`.standard.yml`:

```yaml
plugins:
  - standard-rails

extend_config:
  - .standard-rails.yml
```

`.standard-rails.yml`:

```yaml
require:
  - rubocop-rails

Rails/Pluck:
  Enabled: true
```

`pluck.rb`:

```ruby
# frozen_string_literal: true

models.map { _1[:id] }
```

Then, `standardrb` never reports unexpectedly:

```console
$ standardrb repro.rb
(no output)
```

On the other hand, `rubocop` reports one violation expectedly:

```console
$ rubocop pluck.rb --config .standard-rails.yml
...
pluck.rb:3:8: C: [Correctable] Rails/Pluck: Prefer pluck(:id) over map { _1[:id] }.
models.map { _1[:id] }
       ^^^^^^^^^^^^^^^
...
```

Such as the case above, how should I enable additional cops for RuboCop Rails? Thank you.

### Environment

- standard: 1.29.0
- standard-rails: 0.1.0
- ruby: 3.2.2

### Reproduction via script

Create `repro.rb` with the following content:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile true do
  source "https://rubygems.org"

  gem "standard", "1.29.0"
  gem "standard-rails", "0.1.0"
end

def run(*cmd)
  system(*cmd, exception: true)
end

File.write ".standard.yml", <<~EOF
  plugins:
    - standard-rails

  extend_config:
    - .standard-rails.yml
EOF

File.write ".standard-rails.yml", <<~EOF
  require:
    - rubocop-rails

  Rails/Pluck:
    Enabled: true
EOF

File.write "pluck.rb", <<~EOF
  # frozen_string_literal: true

  models.map { _1[:id] }
EOF

puts ""
puts "### Standard Ruby ###"
puts `standardrb pluck.rb`

puts ""
puts "### RuboCop ###"
puts `rubocop pluck.rb --config .standard-rails.yml`
```

Then, run `repro.rb` as follows:

```shell
docker run --rm -it -v ${PWD}:/work -w /work ruby:3.2.2 ruby repro.rb
```

(or, run just `ruby repro.rb` if you don't mind side-effects for your environment)

**Comment by searls** [comment]
Thanks for asking, @ybiquitous! Just like Standard itself, the design of our plugin system is to _disallow_ changes to rules (including enabling rules that Standard or its plugins disable). The reason for this is so that the behavior of standard and its plugins is identical for the same set of rules. `extend_config` is primarily for custom cops and for RuboCop extensions that lack a Standard plugin.

However, since our presentation April, we haven't yet gone through and turned on additional RuboCop Rails cops, so at the moment I would recommend adopting standard-rails in your case and then come back when we've turned on more cops (like this one) and you can rely on it more fully.

**Comment by ybiquitous** [comment]
Thank you so much for the explanation and advice, @searls. I now understand the current state.
I'll continue to watch for standard-rails!

**Comment by Caleb-T-Owens** [comment]
Hi @searls! Are there still plans to introduce these extra cops?

If there was a concern about breaking existing projects now, could a "stricter" flag be used to enable these extra cops?
