### ISSUE TITLE
👎 on Rails/SaveBang

### ISSUE THREAD

**Issue by jonallured** [standardrb/standard-rails#30]
From the docs:

> This cop identifies possible cases where Active Record save! or related should be used instead of save because the model might have failed to save and an exception is better than unhandled failure.

> This will ignore calls that return a boolean for success if the result is assigned to a variable or used as the condition in an if/unless statement. It will also ignore calls that return a model assigned to a variable that has a call to ‘persisted?`. Finally, it will ignore any call with more than 2 arguments as that is likely not an Active Record call or a Model.update(id, attributes) call.

https://www.rubydoc.info/gems/rubocop/0.44.1/RuboCop/Cop/Rails/SaveBang

I'd like to advocate for removing this from Standard Ruby's plugin for Rails. It's too aggressive and doesn't seem able to focus on only ActiveRecord code.

## 👍 Violations that are AR models

When the violation is on an AR model, then I'm totally fine with a violation being triggered!

```ruby
class Artwork < ApplicationRecord
end

# please save me from myself!
artwork = Artwork.create(params)
```

## 👍 / 👎 Violations in code we own

If we write a class that does not inherit from AR then I should be able to define a method called `create` and that should not be a violation:

```ruby
class ArtworkBuilder
  def create
  end
end

# It's possible that this violation exposes a code smell but I still think I should be able to do this!
artwork = ArtworkBuilder.new.create(params)
```

It's true that since this is code we own we _could_ consider this violation an indication that we have a code smell but imho that's too aggressive. I could live with this but...

## 👎 Violations in code we don't own

The worst-case scenario is when the violation is triggered by code we don't own!

```ruby
stripe_customer_id = Stripe::Customer.create(param[:user_id])
order_attrs = {
  amount_cents: params[:amount_cents],
  stripe_customer_id: stripe_customer_id
}
order = Order.create!(order_attrs)
```

Here I have a gem that contains a class that violates the rule - what should I do to comply with this rule??

**Comment by searls** [comment]
:+1:

**Comment by krystof-k** [comment]
Related issue: rubocop/rubocop-rails#1154.

**Comment by mjankowski** [comment]
This rule is similar to the recently disabled - https://github.com/standardrb/standard-rails/pull/36 - `Rails/PluckId` ... both are disabled in rubocop-rails, and for same reason (can't safely correct, false positives likely for similar reasons).

That said, I think this one is both a) possibly more useful in finding real issues, b) slightly less bad in it's finding false positives - because of the `AllowedReceivers` configuration option.

However, in terms of including in stock standard-rails ... that configuration option is going to be project specific, and there's no way to come up with reasonable defaults there.

Assuming we want a default "don't enable something in standard-rails that rubocop-rails doesnt distribute as enabled", I think this one would be good to disable as well.

**Comment by searls** [comment]
Yeah let's disable it. I'd merge a PR

**Comment by mjankowski** [comment]
Disabled in https://github.com/standardrb/standard-rails/pull/37, can close this.
