### ISSUE TITLE
Disable Rails/EnvironmentVariableAccess in config/initializers?

### ISSUE THREAD

**Issue by danielmorrison** [standardrb/standard-rails#46]
Upgrading `standard-rails` to 1.1.0 has started flagging things like: 

```
config/initializers/stripe.rb:1:18: Rails/EnvironmentVariableAccess: Do not read from `ENV` directly post initialization.
```

IMHO, an initializer is _not_ "post initialization" and is the correct spot for this. 

This comes from https://github.com/rubocop/rubocop-rails/pull/1229 which specifically looks at `config/initializers/**/*.rb` to apply this rule.

What do others think about removing that directory from this check? Happy to whip up a PR if there's enough interest.

**Comment by searls** [comment]
I hate this rule (due to the fact Rails has changed the "correct" way to access ENV vars conventionally 4 times in 10 years) and am absolutely supportive of nixing it. Send a PR to disable

**Comment by dogweather** [comment]
Awesome. I came here with this same issue.

I think this rule has never worked as intended. Rubocop-rails [has disabled it by default](https://github.com/rubocop/rubocop-rails/pull/505) because of a lack of a full example to migrate code.

I suspect that the Rails config and `#config_for` helper do _not_ provide boot-time env var checking. I think it's the opposite: Rails config is a silent failure API. Unknown config names just return `nil`. 

Personally, I `ENV.fetch` in my initializers and store them in namespaced constants. That way, I get some help from the interpreter if I misspell one.

**Comment by dogweather** [comment]
> Send a PR to disable

https://github.com/standardrb/standard-rails/pull/47

**Comment by danielmorrison** [comment]
You're a hero, @dogweather!
